### ISSUE TITLE
Documentation unclear and/or flask-login designed poorly?

### ISSUE THREAD

**Issue by mkonecny** [maxcountryman/flask-login#110]
This is how I understand the current process:

Following the how-to written here: https://flask-login.readthedocs.org/en/latest/#how-it-works
1. We receive post form and validate it is correct. What are we validating here, username and password are correct, or just that they are well-formed (non-empty etc)? If validating password, then that is one hit to the database. 
2. Where is the argument `user` passed to `login_user(user)` coming from? Is it coming from the session cookie, or from the database? It doesn't make sense to load from database because I will need to load the user again later in step 3. It doesn't make sense to use the session because flask-login should abstract that for me??
3. now in the `load_user` callback we have the id of the user, and now have to go back to the database _again_? 

It would be nice if the documentation specified this more explicitly.

**Comment by greiginsydney** [comment]
I'm struggling with the same issue:

The [readme.md](https://github.com/maxcountryman/flask-login/blob/master/README.md) shows `login()` and `request_loader(request)` both validating the password from the form against the `users[email]['password']`, and I can't understand what the point is in the (apparent) double-handling.

Am I missing something basic, or are those two code examples not applicable in tandem in a working solution? 

Thanks.

**Comment by pdneumann** [comment]
I hesitate to make this a new issue, but I wish that the documentation from this github was also on the readthedocs page.  I have a custom authentication method using active directory and could not make flask-login work without a database after pouring over the readthedocs page.  I finally found this github page and was able to get it working in no time.  The simple example of using a dictionary instead of a database was very helpful.
