### ISSUE TITLE
When will 0.3.0 be released?

### ISSUE THREAD

**Issue by robyoung** [maxcountryman/flask-login#218]
It has been over a year since the 0.2.11 release. If there are any features that you'd like added before the release I'd be happy to help.

**Comment by maxcountryman** [comment]
We have no timetable at the moment--there are numerous breaking, undocumented changes that will need to be added to the CHANGELOG before any release is possible and I frankly don't have the time to dredge the commit log. I'd strongly suggest using pinned revs in the meantime. I'm going to close this since it's a duplicate of previous tickets.

**Comment by alanhamlett** [comment]
I could find some time to help go through commits and build the CHANGELOG.

**Comment by maxcountryman** [comment]
@alanhamlett okay, that sounds good.

**Comment by alanhamlett** [comment]
Just noticed we still need to merge the refactor branch into master. I can submit a pull request for that, then do the CHANGELOG in a separate pull request.

**Comment by alanhamlett** [comment]
Created pull request #220 to merge refactor branch into master.

**Comment by maxcountryman** [comment]
`0.3.0` is live on PyPI now.
