### ISSUE TITLE
Another user's account after updating db

### ISSUE THREAD

**Issue by Avrong** [maxcountryman/flask-login#250]
There is a bag in "remember me" function. I have two different DB files, which contain users data. So i can swap them but cookies allow me to access different accounts in both DB.

For example, in first DB i have 1)User_1 and 2) User_2. Cookies allow me to access to user_1's profile. But if i create new database file, (new one contain 1)User_2 and 2)User_1) without changing cookies, i can succesfully open User_2's profile.

![cats](https://cloud.githubusercontent.com/assets/6342851/10865492/196b1568-801e-11e5-81a3-22fc22fd2575.png)

**Comment by alanhamlett** [comment]
This isn't a problem with Flask-Login, you should be returning a unique identifier from your `login_manager.user_loader` function. You are not required to return the user's id so use a unique identifier and return that instead of the user's id.

Check out using [uuid.uuid4()](https://docs.python.org/2/library/uuid.html#uuid.uuid4) instead of integers for your user id. For example, here is [WakaTime](https://wakatime.com/developers/#users)'s SQLAlchemy User model:

```python
import uuid
from sqlalchemy.dialects.postgresql import UUID
from flask.ext.sqlalchemy import SQLAlchemy
from wakatime import app

db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = db.Column(db.String(255), unique=True, nullable=False, index=True)
    password = db.Column(db.String(160))
```

**Comment by maxcountryman** [comment]
Instagram also has [a good article](http://instagram-engineering.tumblr.com/post/10853187575/sharding-ids-at-instagram) about another ID scheme which supports sharding.

**Comment by Avrong** [comment]
Problem only with **remember_token**. How to create it not with DB record's id (not a id column). Create it with 2 columns in db. Or how to change creating method?

**Comment by alanhamlett** [comment]
From your `login_manager.user_loader` you can return any unique string that you want... for example the user's ID concatenated with a session token. That way you can logout users by changing their session token without changing their ID.
