### ISSUE TITLE
How to list logged in users?

### ISSUE THREAD

**Issue by kramer65** [maxcountryman/flask-login#254]
I'm trying to find out how I can list all logged in users but I can't really find anything about it. Does anybody know if this is possible with flask_login? All tips are welcome!

**Comment by maxcountryman** [comment]
That's not something flask-login can do for you, since the session cookie typically lives in a browser. You'll need to design your application in such a way that this information is propagated to a cache or persistence layer on the application backend. You could use signals to attach a callback to login events for example.
