### ISSUE TITLE
Add an example of Alternative Tokens in docs

### ISSUE THREAD

**Issue by Avrong** [maxcountryman/flask-login#285]
Add an example to Alternative Tokens paragraph in documentation: https://flask-login.readthedocs.io/en/latest/#alternative-tokens. I can't understand how use it.

**Comment by alanhamlett** [comment]
I think we should remove `get_auth_token()` because the alternative token bypasses `encode_cookie` and is added as-is without being signed. This could lead to insecure usage of Flask-Login if the user chooses a guessable alternative token.

Instead, we should add an example of returning a session id from the `user_loader` function instead of the user's id.
