### ISSUE TITLE
Reaching Set-Cookie value created by login_user() function

### ISSUE THREAD

**Issue by oyilmaztekin** [maxcountryman/flask-login#325]
I don't know if it is an issue? This is my first time asking something on github. I already asked a question at stackoverflow. I don't get Set-Cookie value created by login_user() function. Controller responds to any CORS and CURL request.  There is no browser submitting form directly so Flask-Login can't put session values automatically as a cookie. I need to get Set-Cookie value login_user() created.

**Comment by davidism** [comment]
`User.get_id()`, assuming you inherited from `UserMixin`. Then load by token instead of cookie, as described in the docs. http://flask-login.readthedocs.io/en/latest/#custom-login-using-request-loader

Please use Stack Overflow for support with your own code. This tracker is for issues with Flask-Login's code. Be sure to include a [Minmal, Complete, and Verifiable Example](http://stackoverflow.com/help/mcve).
