### ISSUE TITLE
current_user is stored as AnonymousUserMixin when passed as argument to MagicMock

### ISSUE THREAD

**Issue by brandones** [maxcountryman/flask-login#326]
If I have a view function that passes `current_user` to another function `bar`, and a test patches `bar` with a MagicMock, `bar` will store `current_user` as `AnonymousUserMixin`.

Prior to the view function returning, current_user will have the correct value, and the MagicMock will show the correct value under call_args. After the view function returns, back in the scope of the test function, the MagicMock's value for call_args will have changed to AnonymousUserMixin.

Minimal reproduction of the bug provided here: https://github.com/brandones/flask-login-bug-minimal-repro

**Comment by lucasdf** [comment]
I checked your code and tried some things out. This is not a bug in Flask-Login. 

The tests that interact with the testing application should be executed inside the same context, otherwise 'call_args' will have a different value when evaluated in the test context. In the tested included in your repository you should execute the requests inside a test_client context:
```python
    def setUp(self):
        self.client = main.app.test_client()

    @mock.patch('main.helper.do_thing')
    def test_check(self, do_thing_mock):
        with self.client as c: # added this line
            self.client.get('/login') # you may replace this by c.get('/login')
            self.client.get('/check')
            self.assertEqual(do_thing_mock.call_count, 1)
            do_thing_mock.assert_called_with(main.user)
``` 

You may want to review the page [Testing](http://flask.pocoo.org/docs/0.12/testing/) in the Flask documentation. The file `test_login.py` from the Flask-Login package also has some interesting examples of testing a Flask application.
