### ISSUE TITLE
Exception: No user_loader has been installed for this LoginManager

### ISSUE THREAD

**Issue by NikolaJankovic** [maxcountryman/flask-login#328]
For apps with multiple User models, is there any way to alter the user_loader / load_user() to be able to distinguish between the models? The standard is 

```
@login_manager.user_loader
def load_user(user_id):
    return User.get(user_id)
```
I need to somehow discern which model the user_id passed belongs to and insert a condition to replace User.get() with the appropriate model.

**Comment by davidism** [comment]
Use `request_loader` instead and pull whatever data you need to tell them apart from the request data. http://flask-login.readthedocs.io/en/latest/#custom-login-using-request-loader

**Comment by NikolaJankovic** [comment]
Using request_loader instead throws the following error:

`Exception: No user_loader has been installed for this LoginManager. Add one with the 'LoginManager.user_loader' decorator.
`

Also, by the time request_loader is called it has no real context to it; the request.view_args dict is empty.

**Comment by davidism** [comment]
I don't have time to fully trace this right now, but it does appear that there's some issues with `_load_from_request`. If `request_callback()` returns `None`, then `reload_user` is called with `user=None` and tries to call `user_loader`, which raises that error.

**Comment by NikolaJankovic** [comment]
For what it's worth, it throws the exception even if request_loader returns a valid User object.

**Comment by sameer-j** [comment]
Any one figured this out? facing the same problem.

**Comment by weixi2008** [comment]
Yes. I also encountered this bug. it throws the exception even if request_loader returns a valid User object. In Release 0.4.1.

**Comment by tiantaozhang** [comment]
Yes. I also encountered this bug too. In Release 0.4.1. The Bug is fixed, but the 0.4.2 is not release yet. How can I do?

**Comment by alanhamlett** [comment]
`-e git://github.com/maxcountryman/flask-login.git@848088a9fc6e8c9c418e8820e072cde6ac81dc00#egg=Flask-Login`

**Comment by phillip-martin** [comment]
Does this mean that `request_loader` is not usable until 0.4.2 is released?

In the mean time, it seems reasonable to use @alanhamlett's proposed `pip install`.

On the other hand, since pip installing a specific branch is not ideal, when is the above mentioned fix expected to be in an official release?

**Comment by phillip-martin** [comment]
This behavior occurred for me because I switched from using `login_manager.user_loader` to `login_manager.request_loader`. I ended up with something like the following:

```python
#@login_manager.user_loader
#def load_user(user_pk):
#    return g.session.query(User).get(user_pk)

@login_manager.request_loader
def request_loader(_request):
    print 'using request loader'  # this would never get called
    return load_user_token(_request)  # custom user loader
```
I had previously logged in a user with `login_user`, the Flask `session` object still had `fresh` and `user_id` key/values. 

While these values were in `session`, I would get an error: `Exception: No user_loader has been installed for this LoginManager. Refer tohttps://flask-login.readthedocs.io/en/latest/#how-it-works for more info.`

using @alanhamlett's pip install example allowed `request_loader` to be called while these values were still in `session`.

I went back to 0.4.1 to see if I could find a solution for current release, as soon as I removed `fresh` and `user_id` from the session, via `logout_user()`, I would no longer get the error mentioned above and my `request_loader` function would be called as expected.

So, an alternative solution I am considering is something like the following. Basically, if a `user_id` is found in `session` allow the user to be loaded as they used to be but `logout_user()` after the request and login the user with the new token method. Admittedly, this is pretty hacky, so I'm still deciding whether to use @alanhamlett's proposed solution or something like this.

```python
@login_manager.user_loader
def load_user(user_pk):
    return g.session.query(User).get(user_pk)

@login_manager.request_loader
def request_loader(_request):
    print 'using request loader'  # this would never get called
    return load_user_token(_request)  # custom user loader

@app.after_request
def app_after_request(response):
    # switch user credentials from session to custom token
    if 'user_id' in session:
        response = login_user_token(response, current_user)  # this is what I use instead of login_user()
        logout_user()  # this removes 'user_id' and 'fresh' from session
    .... # other after_request functionality here
    return response
```

**Comment by alanhamlett** [comment]
@davidism could you help release v0.4.2? Would you like me to submit a PR to update the changelog?

**Comment by dazednconfusing** [comment]
Hi so I installed alanhamlett's fix and now current_user.is_authenticated returns false after I log in with the appropriate Authorization header value for the request_loader

**Comment by alanhamlett** [comment]
Leaving open until 0.4.2 hits pypi to prevent duplicate issues.

**Comment by BZ3R0** [comment]
You must define the decorator at the same file you instantiated the login_manager.
Assuming it's on yourapp.py you shoud do like below:

```
login_manager = LoginManager(app)

@login_manager.user_loader
def load_user(id):
    return User.query.filter_by(user_id=id).first()
```

After that you can delete the ```@login_manager``` decorator and its respect function from your models.

Obs. This works on version 0.4.1 of Flask-Login
