### ISSUE TITLE
User_loader will still be run, even if user login

### ISSUE THREAD

**Issue by syncml** [maxcountryman/flask-login#368]
I'm using flask-login, I thought that the user first login will call user_loader, then get the user information from the session in access will, do not call user_loader, but do not know why, even if the landing, I will call the user_loader, Any wrong setting?

```
SECRET_KEY = "yeah, not actually a secret"
DEBUG = True
app.config.from_object(__name__)
login_manager = LoginManager()
login_manager.anonymous_user = Anonymous
login_manager.login_view = "login"
login_manager.login_message = u"Please log in to access this page."
login_manager.refresh_view = "reauth"
login_manager.init_app(app)

@login_manager.user_loader
def load_user(id):
    return User.query.get(id)
```

**Comment by alanhamlett** [comment]
Please ask questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/flask-login?sort=votes).

User loader is called every request because users can be deleted and shouldn't rely only on the session to stay logged in. If you need more info about this question, please post on [Stackoverflow](https://stackoverflow.com/questions/tagged/flask-login?sort=votes) and I'll help answer your questions there.

**Comment by hellocomrade** [comment]
@alanhamlett 

Could you please elaborate a bit why a web application can't rely on session for the user to stay logged in and on what kind of scenario that a user could be deleted while the user is active?

This issue has not be addressed for many years...

Thanks!

**Comment by alanhamlett** [comment]
@hellocomrade have you seen [Flask-Security](https://flask-security.readthedocs.io/) library? Flask-Login is more of a low-level library to help with the common parts of building your own auth system. If building your own auth system isn't day-to-day then I suggest using Flask-Security.

**Comment by hellocomrade** [comment]
@alanhamlett Thank you for the timely reply and the recommendation! Flask-Security does look like more comprehensive and might have more whistle and bells!

For my current project, persistence layer for authentication is LDAP. So I guess that would be an exploration for me to make it work with Flask-Security.

My workaround using Flask-login, in `@login_manager.user_loader`, instead of loading from backend, User instance will be retrieved from a session entry which is put on when user is successfully authenticated. And then this session entry is invalidated during user logout.

Yes, I understand this workaround ruins the purpose of Flask-login, which saves you from managing session for auth. But at least, I don't have to worry about locking user ldap account and I don't have to store user's ldap password in session.

Based upon what I described, do you see any red light or potential issue? Please advise!

Thanks!

**Comment by alanhamlett** [comment]
Without a timeout in the cookie, will the user be logged in forever even if that user's LDAP entry is deleted? Just want to protect your app from not being able to force logout users.

A better solution would be reading the user from a Redis server that's synced with LDAP whenever LDAP changes. That removes load from your LDAP server, but also prevents users from staying logged in even after their LDAP account is disabled or deleted.

Whatever your decision, GitHub issues is NOT the place to discuss implementation details. Please only use GH issues for bug reports or library feature requests only, or else it becomes unmaintainable. Please ask questions like this on StackOverflow.
