### ISSUE TITLE
Allow customizing next_field

### ISSUE THREAD

**Issue by cancan101** [maxcountryman/flask-login#402]
Right now [`login_url` takes in `next_field`](https://github.com/maxcountryman/flask-login/blob/848088a9fc6e8c9c418e8820e072cde6ac81dc00/flask_login/utils.py#L92) however the [`unauthorized` call does not set it](https://github.com/maxcountryman/flask-login/blob/1bad0f1828fea7b2b09652ea88be0663cdd080e5/flask_login/login_manager.py#L176). Having this customizable would be very useful when redirecting to external services for auth.

**Comment by alanhamlett** [comment]
The [default unauthorized handler](https://github.com/alanhamlett/flask-login/blob/16c3643dd0dc1331dc180d11d2a3449e0964da2a/flask_login/login_manager.py#L175) sets next url to the current request's url. You can also [customize unauthorized handler](http://flask-login.readthedocs.io/en/latest/#flask_login.LoginManager.unauthorized_handler) with your own function.

Closing this for now, since looks like it's solvable with existing configs.

**Comment by cancan101** [comment]
This wasn't about which url to use but what key in the query string to use.

**Comment by cancan101** [comment]
I think yes. To double check, can you show snippet of what you mean?

**Comment by alanhamlett** [comment]
Here's one [copied from the docs](http://flask-login.readthedocs.io/en/latest/#customizing-the-login-process):

```python
@login_manager.unauthorized_handler
def unauthorized():
    # do stuff
    return a_response
```

**Comment by cancan101** [comment]
I was thinking you were suggesting changing [this line](https://github.com/maxcountryman/flask-login/blob/1bad0f1828fea7b2b09652ea88be0663cdd080e5/flask_login/login_manager.py#L176) to:
```python
redirect_url = make_login_url(
    login_view,
    next_url=request.url,
    next_field=config.get('LOGIN_REDIRECT_NEXT_FIELD', LOGIN_REDIRECT_NEXT_FIELD),
)
```

**Comment by alanhamlett** [comment]
Yea that looks good, could you submit a PR with this plus a test added to make sure it's doing what we expect?
