### ISSUE TITLE
Importing with wildcard results in error

### ISSUE THREAD

**Issue by Fallstop** [maxcountryman/flask-login#485]
When importing with a wild card `from flask_login import *` python 3.6.1 errors with 

> ModuleNotFoundError: No module named 'flask_login.0'. 

Importing normally with `import flask_login` works completely fine on my computer.

1. Import with `from flask_login import *`

I can just import them normally as I was just doing this for testing but it would be good to be fixed for the next release.

To summerise:

![image](https://user-images.githubusercontent.com/43323210/79087470-71bb8280-7d93-11ea-97fd-ba861b235d65.png)

(If it's relevant, I'm on Flask v1.1.2 and flask_login v0.5.0)

**Comment by WaizungTaam** [comment]
This problem comes from [\_\_init\_\_.py#L34](https://github.com/maxcountryman/flask-login/blob/master/flask_login/__init__.py#L34)
```python
__all__ = [
    ...
    __version__,
    ...
]
```
`from flask_login import *` also imports `__version__`, which has the value `"0.5.0"`. And apparently, `flask_login.0.5.0` is not a valid module to import. Removing `__version__` from the `__all__` list will solve the problem.
