### ISSUE TITLE
Cookies are not set to secure neither have sameSite set

### ISSUE THREAD

**Issue by Niwla23** [maxcountryman/flask-login#527]
Is there a setting for this? This is a security hole and Firefox even says it won't work in the future.

**Comment by alanhamlett** [comment]
For Flask-Login's remember cookie, use the [REMEMBER_COOKIE_SECURE ](https://flask-login.readthedocs.io/en/latest/#cookie-settings) config. For the login session cookie since that's actually handled by Flask, use Flask's [SESSION_COOKIE_SECURE and SESSION_COOKIE_SAMESITE](https://flask.palletsprojects.com/en/master/security/#set-cookie-options) configs.

**Comment by Leetcore** [comment]
REMEMBER_COOKIE_SECURE works but REMEMBER_COOKIE_SAMESITE doesn't. There was a merge request for that option: https://github.com/maxcountryman/flask-login/pull/453/files on Feb 12. The version in package index is from: Feb 9, 2020. So it's there but not in the pip packages.

**Comment by alanhamlett** [comment]
Yes, you have to install directly from a GitHub commit to get the latest version until it's released on pypi:

```
pip install -e git://github.com/maxcountryman/flask-login.git@c073d3bdeceb2a9c280c421f57c9770ffd9f183a#egg=Flask-Login
```

**Comment by yufernando** [comment]
It would be great to add the fact that the login session cookie is handled by Flask to the documentation, so users know that they should configure SESSION_COOKIE_SECURE, SESSION_COOKIE_SAMESITE, etc.

The only references to cookie configuration in the docs are relative to the REMEMBER_COOKIE.
