### ISSUE TITLE
session['user_id'] is gone.

### ISSUE THREAD

**Issue by luckydonald** [maxcountryman/flask-login#535]
**Describe the bug**
The variable about the current logged in user is gone.

**To Reproduce**
1. Use code from 4.7
2. Update to 5.0
4. The variable is gone.

**Expected behavior**
The information is still there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: python docker
 - Browser does not apply
 - Version 0.5

**Comment by luckydonald** [comment]
Reverting back to 0.4.x fixed it.

**Comment by alanhamlett** [comment]
It's now [session['_user_id']](https://github.com/maxcountryman/flask-login/blob/7ae52f8fadd4bb1870c0ac02bca2e471f79f4c45/flask_login/config.py#L49) because you shouldn't need access to that directly. Instead, use `app.current_user.id`. If you're using `session['_user_id']` in your app, the underscore hints you're using Flask-Login in an unintended way.

More info in https://github.com/maxcountryman/flask-login/pull/470

https://github.com/maxcountryman/flask-login/blob/4745461682b4edc55c626c9f452526cb9a7b4437/CHANGES#L13

**Comment by luckydonald** [comment]
> the underscore hints you're using Flask-Login in an unintended way.
Not in 4.x, lol.
