### ISSUE TITLE
logout_user() does not clean up the remember me cookie

### ISSUE THREAD

**Issue by nikolamirkov** [maxcountryman/flask-login#600]
**Describe the bug**
Hey guys, I've been trying for days to understand why logout_user() is not removing the remember me cookie and therefore current_user.is_authenticated is always True.

**To Reproduce**
1. Add "remember=True" to user_login()
2. Make a request to a logout route containing user_logout() and session.clear()

**Expected behavior**
logout_user() should clean up the remember me cookie

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: any
 - Version: any

**Comment by nikolamirkov** [comment]
BONUS: why does it work if I delete the cookie as follows? thank you so much!

@app.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    resp = make_response(redirect('/'))
    cookie_name = app.config['REMEMBER_COOKIE_NAME']
    domain = app.config['REMEMBER_COOKIE_DOMAIN']
    path = app.config['REMEMBER_COOKIE_PATH']
    resp.delete_cookie(cookie_name, domain=domain, path=path)
    return resp

**Comment by AmirMohammad2003** [comment]
that's because the session.clear() you have added
when `logout_user()` is called it sets the `session['_remember'] = 'clear'`
therefore the cookie gets deleted AFTER ONE REQUEST when login_manager._update_remember_cookie is called
so you just have to delete the `session.clear()` from your code or add the `session['_remember'] = 'clear'` after you clear the session

**Comment by maxcountryman** [comment]
Closing this since this doesn't appear to be a flask-login bug. Please use StackOverflow for future questions related to how to use flask-login.
