### ISSUE TITLE
LoginManager fails because of Werkzeug dependency

### ISSUE THREAD

**Issue by frank1010111** [maxcountryman/flask-login#636]
After Werkzeug updated to v 2.1.0, `LoginManager` cannot import `werkzeug.security.safe_str_cmp`. This is because Werkzeug has removed several deprecated code elements (see <https://github.com/pallets/werkzeug/pull/2276>). The Werkzeug changelog suggests using [hashlib](https://docs.python.org/3/library/hashlib.html) and [hmac](https://docs.python.org/3/library/hmac.html) instead to provide that functionality.

**Comment by endersonmenezes** [comment]
Just for complement, on official documentation says.
```
Deprecated since version 2.0: Will be removed in Werkzeug 2.1. Use [hmac.compare_digest()](https://docs.python.org/3/library/hmac.html#hmac.compare_digest) instead.
```

**Comment by ye** [comment]
Can Flask-Login maintainers release a new version and push it to PyPI please?

This is the commit merged into the main branch. (PR #585 )
https://github.com/maxcountryman/flask-login/commit/322e0dda92c4accca195f6a0d13c5694332deab2

which was merged in July 2021. A new release is long over due!

**Comment by Xevion** [comment]
Yup, this just gave me the run around trying to figure out what went wrong with Flask-Login a day after it was working fine.
It is my understanding that what happened today can be adequately termed as a "fuck up" by the developers who work on Flask-Login and supervise it, correct? Not anyone in here, most likely, but the people who have the ability to merge PRs and such.

Werkzeug developers seem to be essentially telling anyone who got hit with this error today should've seen it coming:
[https://github.com/pallets/werkzeug/issues/2359#issuecomment-1081004695](https://github.com/pallets/werkzeug/issues/2359#issuecomment-1081004695)

**Comment by ye** [comment]
@Xevion no, I chalk this up as a f**k up on Werkzeug's maintainer because he has a tendency to introduce and release Pallet softwares (he's the maintainer for a lot of them) in a fast-and-furious style without giving the depending package maintainers enough time to catch up. By comparison, Python community has to wait over a decade before everyone catches up on Python3 to deprecate Python2, but Werkzeug couldn't care less and just released breaking changes in a short few months. He also has a tendency closing tickets that he deemed unworthy or don't care - my-way-or-the-highway style. No caring open source community project maintainer does things like that. Breaking changes should be in a 3.x version not 2.x version.

Not only `werkzeug.security.safe_str_cmp` was removed, he removed a bunch more, `as_tuple`, as another example. This makes you wonder what's with the hastiness?

**Comment by Xevion** [comment]
> @Xevion no, I chalk this up as a f**k up on Werkzeug's maintainer because he has a tendency to introduce and release Pallet softwares (he's the maintainer for a lot of them) in a fast-and-furious style without giving the depending package maintainers enough time to catch up.

Huh. I don't care/have the time enough to actually go through and find how much time the `safe_str_cmp` was deprecated, but I am a little curious now. How long precisely did `flask-login` have to notice (and prepare for) what has happened here? *If you care, that is.

**Comment by davidism** [comment]
We're actively working on updating this project and will make a new release soon. I've locked this as the discussion was not moving in a productive direction.

**Comment by davidism** [comment]
Duplicate of #584
