### ISSUE TITLE
incompatible with werkzeug 2.2.0, can't import parse_rule

### ISSUE THREAD

**Issue by frantisekz** [maxcountryman/flask-login#686]
Importing flask-login with werkzeug 2.2.0a1 ends up with:

```
Traceback:
/usr/lib64/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_packager_dashboard_pagure.py:4: in <module>
    from oraculum.utils import pagure
oraculum/__init__.py:29: in <module>
    from flask_login import LoginManager
/usr/lib/python3.11/site-packages/flask_login/__init__.py:12: in <module>
    from .login_manager import LoginManager
/usr/lib/python3.11/site-packages/flask_login/login_manager.py:35: in <module>
    from .utils import _create_identifier
/usr/lib/python3.11/site-packages/flask_login/utils.py:14: in <module>
    from werkzeug.routing import parse_rule
E   ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/usr/lib/python3.11/site-packages/werkzeug/routing/__init__.py)
```

**Comment by davidism** [comment]
I'm trying to figure out what that code does in the first place. I think it's trying to say "if there's a dynamic subdomain or host matching in the current rule, apply that same argument to the login rule." But there's surely a better way to go about that.

**Comment by lazeebee** [comment]
@davidism setup.py is still saying "Werkzeug>=1.0.1"...

**Comment by najibfahs** [comment]
I have just experienced the same problem described above. My code was working yesterday, then today I ran _pipenv install wtforms-sqlalchemy_ and this seems to have updated _Werkzeug_ to 2.2.1 released on 7/23. As a result, my Flask code started failing: ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' 

At first, I did not know what it was, until I found this page. So I did the following twice (2 different virtual env.):
pipenv install Werkzeug=='2.1.2' and this replaced the 2.2.0
then my code was fine! no more errors.

I created the 2nd environment to reinstall all libraries from scratch thinking something corrupted the 1st environment. but no, the same issue was in the 2nd env.

Thought I would share this frustrating experience.

**Comment by potiuk** [comment]
Same here. We suddenly got a number of Airlfow PRs failing over the weekend after new werkzeug 2.2.0 was released. Luckily it only impacts some parts of our pipeline (as we deliberately protect against such cases), but It will still impact a number of our users who do not use "constraints" (which is the only way we can use to protect).

Not sure if this is a Werkzeug or flask-login problem but it's not the first time when those two stopped working at some point of time (It happened I think for the 3rd time over last few years). So maybe that would be good idea that maintainer of the two project talk to each other and agree on some "non-breaking" rules that the two projects will follow - if both of those projects are so "fundamental" for a number of other projects??

It could either be as simple as putting an upper-bound in flask-login, to limit to "known-working werkzeug version" following some agreement on when breaking changes are introduced in werkzeug (maybe starting following SemVer is a good idea) and generally agreeing what is teh "API" of werkzeug that is supposed to be non-braking.

Maybe you can just talk to each other and agree ?

**Comment by potiuk** [comment]
> all something you can avoid easily by pinning your transitive dependencies...

We do already. But pinning dependencies is only half-solving the problem. The problem is that regardless if you are using pinning or not when you release your sftware, you usually do not pin your dependencies in development (unless you want your dependencies to go stale). So such a breaking release releases PR/development workflow more than release workflow.

The main problem is that things break in random moments of when Flask-Login + Werkzeug are released - without even either of them bumping the major version (which is usually an indication of breaking chnages if you follow Semver). So if you are building your development workflow (where you do not want to pin the dependencies), there is no "reasonable" approach you can make to a) get latest versions with bugixes and b) get it non-breaking PRs of your users. It does not have to be "upper-binding". It might be simple agreement on what constitute of an API of werkzeug so that MINOR versions do not break the APIs.

So my gentle proposal (I am not pushing - this was merely a suggestion that it would be much better for the community of your users if you agree some ways how we can "sanely" rely on the combo of flask-login and werkzeug not braking compatibility. It does not have to upper-binding, but some way of indicating to your users how they can constraint their dependencies in their development workflow to keep your development environment "working" - and not prone to external depenencies breaking your workflow.

We are using sophisticated mechanism to control our dependencies. In our case all our released versions of Airflow have automatically generated constraint files. And this is the only reason why such an incompatibility is not causing us bigger troubles. There are good reasons we cannot pin transitive dependencies in Airlfow "setup.py" and "setup.cfg" (because airlfow is both a library and application) but we implemented constraint mechanism which very much shield us from such breakages induced by external dependency changes.  When we did not have them, such Werkzeug breakeges caused much more trouble for us, that's why we implemented constraints. This is a note from our nnouncements back from Feb 2020, were we had to bend the ASF rules on releases and release 1.10.9 same day as 1.10.8 becaue Werkzeug release broke it: https://airflow.apache.org/announcements/#feb-7-2020

> Feb 7, 2020
>   We’ve just released Airflow v1.10.8
>    and
>   We’ve just released Airflow 1.10.9 (this one is a quick fix to work around the breaking release of Werkzeug 1.0)

So I do realise importance of pinnning, but I am talking about something different here.

BTW. If you are insterested why pinning "install required" dependencies is not always best you can read more here: 
https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#dependency-management
or you can read the talk I gave about it few months ago:

https://www.youtube.com/watch?v=_SjMdQLP30s&t=2549s - "Managing dependencies at Scale".

**Comment by ThiefMaster** [comment]
> you usually do not pin your dependencies in development (unless you want your dependencies to go stale). So such a breaking release imacts PR/development workflow more than release workflow.

IMHO you should use the same deps for dev as you use for production, and be more explicit about updating dependencies at some point (e.g. a `pip-compile -U`) where you then check if anything broke, look through changelogs, etc. and commit the new pins. With unpinned dev dependencies you never know if/when something is going to break, and it's generally a mess when working in a team where one team member has some problem, while another cannot reproduce it since they have other dependency versions...

**Comment by potiuk** [comment]
> IMHO you should use the same deps for dev as you use for production, and be more explicit about updating dependencies at some point (e.g. a `pip-compile -U`) where you then check if anything broke, look through changelogs, etc. and commit the new pins. With unpinned dev dependencies you never know if/when something is going to break, and it's generally a mess when working in a team where one team member has some problem, while another cannot reproduce it since they have other dependency versions...

Please watch my talk why it is impossible for us (and I do recommend that your advises are based on resarch first). 

We have ~ 600 depenencies in airflow with consittue ~20 updates per week and it woudl be impossible to keep the manually updated. But we do have it implemented as you say - only automatically. And we DO keep a consistent set of dependencies for development (we keep all the 600 dependencies updated automatically for "most" developers and "most PRs" of our developers. We even have a super sophisticated solution that automatically builds Dev Docker container with all the deps - and ONLY upgrade the dependencies when all the tests are passing. So you are advising something that we have done long time ago automated and run for years already. 

And again - I am not talking about this. This does not work for some of PRs that are updating other dependencies  - this is where you have problems. This problem affected maybe 10% of our PRs. So this is not a huge problem for us.

What I am merely suggesting - is that the two projects talk to each otehr and agree some rules that will enable us to avoid breaking even the 10% of the PRs. This has happened not only once, so as a good community citizen, I suggest that both projects can do better when cooperating on that - no more, no less.

**Comment by potiuk** [comment]
FYI @ThiefMaster You can see here https://github.com/apache/airflow/tree/constraints-main - look especially at the history. This is precisely what you describe - i.e. consistent set of dev dependencies. And if you look at the history, you will see that those sets are regularly updated (sometimes 3 times a day) when our automated tests all succeed and we know we can safely update.

**Comment by davidism** [comment]
See #663 which introduced this issue. #657 reported that the login URL contained both the literal next URL as well as extra query args for current view args, like `id=34`. I think we can just revert that for now.

**Comment by davidism** [comment]
The behavior introduced by #462 was incorrect, I'm going to revert that (and by extension #663). 0.6.2 coming soon.

**Comment by davidism** [comment]
https://pypi.org/project/Flask-Login/0.6.2/
