### ISSUE TITLE
current_user instance is of LocalProxy type

### ISSUE THREAD

**Issue by estebanfeldman** [maxcountryman/flask-login#9]
Hi, when using current_user instance I was having a weird bug with MongoEngine, then I decided to debug and when checking:

``` python
ipdb> type(current_user)
<class 'werkzeug.local.LocalProxy'>
```

That's not desired if I will use it directly. MongoEngine complains when using that instance during query/update, etc... 
Is there any way to unwrap the proxy? Right now I have to query to the DB to get the real object.

Thanks

**Comment by pawlowskimichal** [comment]
Why can't we have a simple stupid function like `get_current_user` (returning the result of `LoginManager.user_loader`) that, unlike a proxy, will just *work* predictably in all cases?

Proxies are evil.

**Comment by davidism** [comment]
> Proxies are evil.

Reconsider using Flask then.

**Comment by asteinlein** [comment]
+1 to having a `get_current_user()` or some such that returns the current object of the proxy -- I really don't understand the controversy.

I was just bit by this exact thing and found this issue, when using Flask-OAuthlib to store grant objects in a Redis cache. A grant must be created for the current user (and Flask-OAuthlib expects the user object on the grant, not just an identifier/username). But, just as evident by this discussion, I can't do `grant = Grant(user=current_user, ...)` and save that grant to Redis, because of this issue.

To be honest, I don't quite understand the reasoning behind having a `current_user` global proxy instead of putting the current user into Flask's `g`, which seems designed for stuff like this. Anyhow, that's a design decision that has long since been made, so OK. But why not make users lives easier by exposing a `get_current_user()` that doesn't affect this library's proxy usage, or existing code using this library, at all?

**Comment by maxcountryman** [comment]
@asteinlein there's nothing stopping you from implementing that yourself. I'm locking this topic now.
